In [4]:
import numpy as np
import tensorflow as tf
import pprint

In [5]:
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [6]:
# 1차원 배열
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim) # rank 몇차원인지..
print(t.shape) # 몇개의 요소를 가지고 있는지
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


In [7]:
# 2차원 배열
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [8]:
t = tf.constant([1, 2, 3, 4])  # 1차원
tf.shape(t).eval()

array([4])

In [9]:
t = tf.constant([[1, 2],     # 2차원
[3, 4]])
tf.shape(t).eval()

array([2, 2])

In [12]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])  
# rank=4 -> shape(x1, x2, x3, x4) 형태
# 제일 안쪽 요소의 갯수를 x4 -> x1순으로 채워나감
tf.shape(t).eval()

array([1, 2, 3, 4])

In [13]:
[
    [
        [
            [1, 2, 3, 4], 
            [5, 6, 7, 8], 
            [9, 10, 11, 12]
        ],
        [
            [13, 14, 15, 16], 
            [17, 18, 19, 20], 
            [21, 22, 23, 24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [14]:
matrix1 = tf.constant([[1., 2.], [3., 4.]]) # matmul
matrix2 = tf.constant([[1.], [2.]])
print("Metrix 1 shape", matrix1.shape)
print("Metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Metrix 1 shape (2, 2)
Metrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [15]:
(matrix1 * matrix2).eval() # multiply

array([[1., 2.],
       [6., 8.]], dtype=float32)

In [16]:
matrix1 = tf.constant([[3., 3.]]) # broadcasting
matrix2 = tf.constant([[2., 2.]])
(matrix1 + matrix2).eval()

array([[5., 5.]], dtype=float32)

In [17]:
matrix1 = tf.constant([[1., 2.]]) # shape이 다른 값들 끼리의 연산 가능
matrix2 = tf.constant(3.)  # [[3, 3]]
(matrix1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[1., 2.]]) # rank가 다른 값들 끼리의 연산 가능
matrix2 = tf.constant([3., 4.]) 
(matrix1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [19]:
matrix1 = tf.constant([[1., 2.]]) # rank는 같으나 형태가 다른 경우의 연산 가능
matrix2 = tf.constant([[3.], [4.]]) 
(matrix1 + matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

In [20]:
tf.reduce_mean([1, 2], axis=0).eval() 
# 어떤 행렬에 있는 여러개의 값을 하나로 줄여줌

1

In [21]:
x = [[1., 2.],[3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [22]:
tf.reduce_mean(x, axis=0).eval() 
# axis 0을 기준으로 평균 구하기, 1과 3의 평균, 2와 4의 평균

array([2., 3.], dtype=float32)

In [23]:
tf.reduce_mean(x, axis=1).eval() 
# axis 1을 기준으로 평균 구하기, 1과 2의 평균, 3과 4의 평균

array([1.5, 3.5], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=-1).eval() 
# 가장 안쪽에 있는 axis를 기준으로 평균 구하기

array([1.5, 3.5], dtype=float32)

In [25]:
x = [[1., 2.], [3., 4.]]
tf.reduce_sum(x).eval()

10.0

In [27]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [28]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [29]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [30]:
x = [[0, 1, 2], [2, 1, 0]] # axis 0을 기준으로 큰 값의 위치 출력
tf.argmax(x, axis=0).eval() # 0 < 2 / 1 = 1 / 2 > 0 

array([1, 0, 0], dtype=int64)

In [31]:
tf.argmax(x, axis=1).eval() 
# axis 1을 기준으로 큰 값의 위치 출력
# [0, 1, 2] 중 index 2 / [2, 1, 0] 중 index 0

array([2, 0], dtype=int64)

In [32]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)