In [1]:
import tensorflow as tf

In [6]:
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

In [7]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [9]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [10]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})  # x_data, y_data는 training data
        print(step, cost_val, W_val)

    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))                   # x_test, y_test는 test data

-0.88286203 -0.889304   -1.2694972 ]]
50 0.9537467 [[-0.6810853  -0.8147218  -0.94934464]
 [-0.26618537 -0.46253935 -0.17794707]
 [-0.8807556  -0.8871345  -1.2737731 ]]
51 0.9482589 [[-0.6890328  -0.8197381  -0.93638086]
 [-0.26514545 -0.46245795 -0.17906842]
 [-0.87865734 -0.88502383 -1.277982  ]]
52 0.9428652 [[-0.6969274  -0.82469684 -0.9235275 ]
 [-0.26411575 -0.46233872 -0.18021733]
 [-0.87656796 -0.8829703  -1.282125  ]]
53 0.9375644 [[-0.7047697  -0.82959837 -0.9107837 ]
 [-0.26309547 -0.4621835  -0.1813928 ]
 [-0.87448734 -0.8809728  -1.286203  ]]
54 0.9323543 [[-0.71256006 -0.8344429  -0.8981488 ]
 [-0.26208463 -0.4619933  -0.18259385]
 [-0.8724162  -0.87902975 -1.2902173 ]]
55 0.92723376 [[-0.72029907 -0.83923084 -0.88562185]
 [-0.26108256 -0.46176973 -0.1838195 ]
 [-0.8703545  -0.87714    -1.2941687 ]]
56 0.9222006 [[-0.7279873  -0.8439624  -0.8732021 ]
 [-0.26008907 -0.46151403 -0.18506871]
 [-0.8683025  -0.87530214 -1.2980585 ]]
57 0.9172537 [[-0.7356252  -0.8486379  -0.86