In [1]:
import tensorflow as tf
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973], 
[823.02002, 828.070007, 1828100, 821.655029, 828.070007],
[819.929993, 824.400024, 1438100, 818.97998, 824.159973],
[816, 820.958984, 1008100, 815.48999, 819.23999],
[819.359985, 823, 1188100, 818.469971, 818.97998],
[819, 823, 1198100, 816, 820.450012],
[811.700012, 815.25, 1098100, 809.780029, 813.669983],
[809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = MinMaxScaler().fit_transform(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [19]:
X = tf.placeholder("float", shape=[None, 4])
Y = tf.placeholder("float", shape=[None, 1])
W = tf.Variable(tf.random_normal([4, 1], name='weight'))
b = tf.Variable(tf.random_normal([1], name='bias'))

In [21]:
hypothesis = tf.matmul(X, W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [23]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "nPrediction:\n", hy_val)

0 Cost:  321790900000.0 nPrediction:
 [[-400577.6 ]
 [-803219.1 ]
 [-632512.8 ]
 [-444297.75]
 [-523089.94]
 [-527461.94]
 [-483668.  ]
 [-614963.  ]]
1 Cost:  3.535447e+26 nPrediction:
 [[1.3263356e+13]
 [2.6700497e+13]
 [2.1004317e+13]
 [1.4723914e+13]
 [1.7352920e+13]
 [1.7498976e+13]
 [1.6038417e+13]
 [2.0420093e+13]]
2 Cost:  inf nPrediction:
 [[-4.3963183e+20]
 [-8.8502404e+20]
 [-6.9621639e+20]
 [-4.8804404e+20]
 [-5.7518599e+20]
 [-5.8002718e+20]
 [-5.3161500e+20]
 [-6.7685155e+20]]
3 Cost:  inf nPrediction:
 [[1.4572190e+28]
 [2.9335312e+28]
 [2.3077031e+28]
 [1.6176877e+28]
 [1.9065314e+28]
 [1.9225783e+28]
 [1.7621096e+28]
 [2.2435156e+28]]
4 Cost:  inf nPrediction:
 [[-4.8301489e+35]
 [-9.7235852e+35]
 [-7.6491939e+35]
 [-5.3620444e+35]
 [-6.3194557e+35]
 [-6.3726452e+35]
 [-5.8407501e+35]
 [-7.4364354e+35]]
5 Cost:  inf nPrediction:
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
6 Cost:  nan nPrediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
